#!/usr/bin/env python3
"""Cross-actor target-scope regressions on the existing actor-correction browser harness.

This file adds only scenario data. It reuses the same Stödassistenten build, browser
harness, assertions and routing runtime from test_actor_correction_company_browser.
"""

from __future__ import annotations

import test_actor_correction_company_browser as base


EXTRA_SCENARIOS = [
    {
        "id": "sv-association-target-positive",
        "lang": "sv",
        "width": 390,
        "text": "Jag söker bidrag för vår förening.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
    },
    {
        "id": "sv-association-target-excluded-asks-once",
        "lang": "sv",
        "width": 768,
        "text": "Jag söker bidrag, men inte för vår förening.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },
    {
        "id": "sv-association-target-excluded-student-wins",
        "lang": "sv",
        "width": 1024,
        "text": "Jag söker bidrag, men inte för vår förening. Jag är student.",
        "expect_question": False,
        "expect_actor": "study",
        "reject_actor": "association",
        "expect_intent": "funding",
    },
    {
        "id": "ar-association-target-positive",
        "lang": "ar",
        "width": 390,
        "text": "أبحث عن دعم مالي لجمعية.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-association-target-excluded-asks-once",
        "lang": "ar",
        "width": 768,
        "text": "أبحث عن دعم مالي، لكن ليس لجمعية.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-association-target-excluded-student-wins",
        "lang": "ar",
        "width": 1024,
        "text": "أبحث عن دعم مالي، لكن ليس لجمعية. أنا طالب.",
        "expect_question": False,
        "expect_actor": "study",
        "reject_actor": "association",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-association-target-positive",
        "lang": "fa",
        "width": 390,
        "text": "برای انجمن من کمک مالی می‌خواهم.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-association-target-excluded-asks-once",
        "lang": "fa",
        "width": 768,
        "text": "کمک مالی می‌خواهم، اما نه برای انجمن من.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-association-target-excluded-student-wins",
        "lang": "fa",
        "width": 1024,
        "text": "کمک مالی می‌خواهم، اما نه برای انجمن من. من دانشجو هستم.",
        "expect_question": False,
        "expect_actor": "study",
        "reject_actor": "association",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "sv-property-target-positive",
        "lang": "sv",
        "width": 390,
        "text": "Jag söker bidrag för min BRF.",
        "expect_question": False,
        "expect_actor": "property_actor",
        "expect_intent": "funding",
    },
    {
        "id": "sv-property-target-excluded-asks-once",
        "lang": "sv",
        "width": 768,
        "text": "Jag söker bidrag, men inte för min BRF.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },
    {
        "id": "sv-property-target-excluded-student-wins",
        "lang": "sv",
        "width": 1024,
        "text": "Jag söker bidrag, men inte för min BRF. Jag är student.",
        "expect_question": False,
        "expect_actor": "study",
        "reject_actor": "property_actor",
        "expect_intent": "funding",
    },
    {
        "id": "ar-property-target-positive",
        "lang": "ar",
        "width": 390,
        "text": "أبحث عن دعم مالي لمالك العقار.",
        "expect_question": False,
        "expect_actor": "property_actor",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-property-target-excluded-asks-once",
        "lang": "ar",
        "width": 768,
        "text": "أبحث عن دعم مالي، لكن ليس لمالك العقار.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-property-target-excluded-student-wins",
        "lang": "ar",
        "width": 1024,
        "text": "أبحث عن دعم مالي، لكن ليس لمالك العقار. أنا طالب.",
        "expect_question": False,
        "expect_actor": "study",
        "reject_actor": "property_actor",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-property-target-positive",
        "lang": "fa",
        "width": 390,
        "text": "برای مالک ساختمان کمک مالی می‌خواهم.",
        "expect_question": False,
        "expect_actor": "property_actor",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-property-target-excluded-asks-once",
        "lang": "fa",
        "width": 768,
        "text": "کمک مالی می‌خواهم، اما نه برای مالک ساختمان.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-property-target-excluded-student-wins",
        "lang": "fa",
        "width": 1024,
        "text": "کمک مالی می‌خواهم، اما نه برای مالک ساختمان. من دانشجو هستم.",
        "expect_question": False,
        "expect_actor": "study",
        "reject_actor": "property_actor",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "sv-stale-association-target-excluded-asks-once",
        "lang": "sv",
        "width": 1280,
        "actor_type": "association",
        "text": "Jag söker bidrag, men inte för vår förening.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },
    {
        "id": "sv-stale-property-target-excluded-asks-once",
        "lang": "sv",
        "width": 1280,
        "actor_type": "property_actor",
        "text": "Jag söker bidrag, men inte för min BRF.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },

    # Study application-target scope: current identity is not automatically the target.
    {
        "id": "sv-study-target-positive",
        "lang": "sv",
        "width": 390,
        "text": "Jag är student och söker bidrag för mina studier.",
        "expect_question": False,
        "expect_actor": "study",
        "expect_intent": "funding",
    },
    {
        "id": "sv-study-target-excluded-asks-once",
        "lang": "sv",
        "width": 768,
        "text": "Jag är student och söker bidrag, men inte för mina studier.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },
    {
        "id": "sv-study-target-excluded-company-wins",
        "lang": "sv",
        "width": 1024,
        "text": "Jag är student och söker bidrag, men inte för mina studier. Jag driver ett företag.",
        "expect_question": False,
        "expect_actor": "company",
        "reject_actor": "study",
        "expect_intent": "funding",
    },
    {
        "id": "sv-stale-study-target-excluded-asks-once",
        "lang": "sv",
        "width": 1280,
        "actor_type": "student",
        "text": "Jag söker bidrag, men inte för mina studier.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },
    {
        "id": "ar-study-target-positive",
        "lang": "ar",
        "width": 390,
        "text": "أنا طالب وأبحث عن دعم مالي لدراستي.",
        "expect_question": False,
        "expect_actor": "study",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-study-target-excluded-asks-once",
        "lang": "ar",
        "width": 768,
        "text": "أنا طالب وأبحث عن دعم مالي، لكن ليس لدراستي.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-study-target-excluded-company-wins",
        "lang": "ar",
        "width": 1024,
        "text": "أنا طالب وأبحث عن دعم مالي، لكن ليس لدراستي. لدي شركة.",
        "expect_question": False,
        "expect_actor": "company",
        "reject_actor": "study",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-stale-study-target-excluded-asks-once",
        "lang": "ar",
        "width": 1280,
        "actor_type": "student",
        "text": "أبحث عن دعم مالي، لكن ليس لدراستي.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-study-target-positive",
        "lang": "fa",
        "width": 390,
        "text": "من دانشجو هستم و برای تحصیلم کمک مالی می‌خواهم.",
        "expect_question": False,
        "expect_actor": "study",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-study-target-excluded-asks-once",
        "lang": "fa",
        "width": 768,
        "text": "من دانشجو هستم و کمک مالی می‌خواهم، اما نه برای تحصیلم.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-study-target-excluded-company-wins",
        "lang": "fa",
        "width": 1024,
        "text": "من دانشجو هستم و کمک مالی می‌خواهم، اما نه برای تحصیلم. شرکت من برای این حمایت درخواست می‌دهد.",
        "expect_question": False,
        "expect_actor": "company",
        "reject_actor": "study",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-stale-study-target-excluded-asks-once",
        "lang": "fa",
        "width": 1280,
        "actor_type": "student",
        "text": "کمک مالی می‌خواهم، اما نه برای تحصیلم.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "funding",
        "expect_rtl": True,
    },

    # Employee application-target scope: employment identity is not automatically the target.
    {
        "id": "sv-employee-target-positive",
        "lang": "sv",
        "width": 390,
        "text": "Jag är anställd och söker bidrag för mitt jobb.",
        "expect_question": False,
        "expect_actor": "employee",
        "expect_intent": "funding",
    },
    {
        "id": "sv-employee-target-excluded-asks-once",
        "lang": "sv",
        "width": 768,
        "text": "Jag är anställd och söker bidrag, men inte för mitt jobb.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },
    {
        "id": "sv-employee-target-excluded-company-wins",
        "lang": "sv",
        "width": 1024,
        "text": "Jag är anställd och söker bidrag, men inte för mitt jobb. Jag driver ett företag.",
        "expect_question": False,
        "expect_actor": "company",
        "reject_actor": "employee",
        "expect_intent": "funding",
    },
    {
        "id": "sv-stale-employee-target-excluded-asks-once",
        "lang": "sv",
        "width": 1280,
        "actor_type": "employee",
        "text": "Jag söker bidrag, men inte för mitt jobb.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },
    {
        "id": "ar-employee-target-positive",
        "lang": "ar",
        "width": 390,
        "text": "أنا موظف وأبحث عن دعم مالي لعملي.",
        "expect_question": False,
        "expect_actor": "employee",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-employee-target-excluded-asks-once",
        "lang": "ar",
        "width": 768,
        "text": "أنا موظف وأبحث عن دعم مالي، لكن ليس لعملي.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-employee-target-excluded-company-wins",
        "lang": "ar",
        "width": 1024,
        "text": "أنا موظف وأبحث عن دعم مالي، لكن ليس لعملي. لدي شركة.",
        "expect_question": False,
        "expect_actor": "company",
        "reject_actor": "employee",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-stale-employee-target-excluded-asks-once",
        "lang": "ar",
        "width": 1280,
        "actor_type": "employee",
        "text": "أبحث عن دعم مالي، لكن ليس لعملي.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-employee-target-positive",
        "lang": "fa",
        "width": 390,
        "text": "من کارمند هستم و برای کارم کمک مالی می‌خواهم.",
        "expect_question": False,
        "expect_actor": "employee",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-employee-target-excluded-asks-once",
        "lang": "fa",
        "width": 768,
        "text": "من کارمند هستم و کمک مالی می‌خواهم، اما نه برای کارم.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-employee-target-excluded-company-wins",
        "lang": "fa",
        "width": 1024,
        "text": "من کارمند هستم و کمک مالی می‌خواهم، اما نه برای کارم. شرکت من برای این حمایت درخواست می‌دهد.",
        "expect_question": False,
        "expect_actor": "company",
        "reject_actor": "employee",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-stale-employee-target-excluded-asks-once",
        "lang": "fa",
        "width": 1280,
        "actor_type": "employee",
        "text": "کمک مالی می‌خواهم، اما نه برای کارم.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
]

base.SCENARIOS.extend(EXTRA_SCENARIOS)


if __name__ == "__main__":
    raise SystemExit(base.main())
