#!/usr/bin/env python3
"""Arabic association-member correction regression on the shared actor harness.

Scenario-only extension of the existing Stödassistenten actor-correction browser test.
It does not implement routing or matching logic.
"""

from __future__ import annotations

import test_actor_correction_company_browser as base


EXTRA_SCENARIOS = [
    {
        "id": "ar-stale-association-member-corrected-to-student",
        "lang": "ar",
        "width": 390,
        "actor_type": "association",
        "text": "لست عضوًا في جمعية، أنا طالب الآن وأبحث عن منحة دراسية.",
        "expect_question": False,
        "expect_actor": "study",
        "reject_actor": "association",
        "expect_intent": "scholarship",
        "expect_rtl": True,
    },
    {
        "id": "ar-stale-association-member-negated-without-replacement-asks-once",
        "lang": "ar",
        "width": 1280,
        "actor_type": "association",
        "text": "لست عضوًا في جمعية وأبحث عن تمويل.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-current-association-member-context-remains",
        "lang": "ar",
        "width": 768,
        "actor_type": "association",
        "text": "أنا عضو في جمعية وأبحث عن تمويل.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "sv-current-association-self-positive",
        "lang": "sv",
        "width": 390,
        "text": "Jag är med i föreningen och söker bidrag.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
    },
    {
        "id": "ar-current-association-self-positive",
        "lang": "ar",
        "width": 768,
        "text": "أنا عضو في جمعية وأبحث عن تمويل.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-current-association-self-positive",
        "lang": "fa",
        "width": 1280,
        "text": "من عضو انجمن هستم و به کمک مالی نیاز دارم.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "sv-third-party-association-membership-asks-once",
        "lang": "sv",
        "width": 1280,
        "text": "Min syster är med i föreningen och jag söker bidrag.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },
    {
        "id": "ar-third-party-association-membership-asks-once",
        "lang": "ar",
        "width": 390,
        "text": "أختي عضوة في جمعية وأنا أبحث عن تمويل.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-third-party-association-membership-asks-once",
        "lang": "fa",
        "width": 768,
        "text": "خواهرم عضو انجمن است و من به کمک مالی نیاز دارم.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "sv-mixed-self-and-third-party-association-keeps-self-role",
        "lang": "sv",
        "width": 390,
        "text": "Min syster är medlem i föreningen. Jag är också medlem i föreningen och söker bidrag.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
    },
    {
        "id": "ar-mixed-self-and-third-party-association-keeps-self-role",
        "lang": "ar",
        "width": 768,
        "text": "أختي عضوة في جمعية وأنا أيضًا عضوة في الجمعية وأبحث عن تمويل.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-mixed-self-and-third-party-association-keeps-self-role",
        "lang": "fa",
        "width": 1280,
        "text": "خواهرم عضو انجمن است و من هم عضو انجمن هستم و به کمک مالی نیاز دارم.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "sv-association-funding-source-is-not-applicant-mobile",
        "lang": "sv",
        "width": 390,
        "text": "Jag söker bidrag från föreningen.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },
    {
        "id": "sv-association-funding-source-is-not-applicant-desktop",
        "lang": "sv",
        "width": 1280,
        "text": "Jag söker bidrag från föreningen.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "funding",
    },
    {
        "id": "ar-association-funding-source-is-not-applicant-mobile",
        "lang": "ar",
        "width": 390,
        "text": "أبحث عن دعم مالي من الجمعية.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "ar-association-funding-source-is-not-applicant-desktop",
        "lang": "ar",
        "width": 1280,
        "text": "أبحث عن دعم مالي من الجمعية.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-association-funding-source-is-not-applicant-mobile",
        "lang": "fa",
        "width": 390,
        "text": "من از انجمن کمک مالی می‌خواهم.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "fa-association-funding-source-is-not-applicant-desktop",
        "lang": "fa",
        "width": 1280,
        "text": "من از انجمن کمک مالی می‌خواهم.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "funding",
        "expect_rtl": True,
    },
    {
        "id": "sv-association-scholarship-source-is-not-applicant",
        "lang": "sv",
        "width": 390,
        "text": "Jag söker föreningens stipendium.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "scholarship",
    },
    {
        "id": "ar-association-scholarship-source-is-not-applicant",
        "lang": "ar",
        "width": 768,
        "text": "أبحث عن منحة الجمعية.",
        "expect_question": True,
        "question_token": "من",
        "expect_intent": "scholarship",
        "expect_rtl": True,
    },
    {
        "id": "fa-association-scholarship-source-is-not-applicant",
        "lang": "fa",
        "width": 1280,
        "text": "برای بورسیه انجمن درخواست می‌دهم.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "scholarship",
        "expect_rtl": True,
    },
    {
        "id": "sv-association-scholarship-from-source-is-not-applicant",
        "lang": "sv",
        "width": 1280,
        "text": "Jag söker stipendium från föreningen.",
        "expect_question": True,
        "question_token": "vem",
        "expect_intent": "scholarship",
    },
    {
        "id": "fa-association-scholarship-from-source-is-not-applicant",
        "lang": "fa",
        "width": 390,
        "text": "برای بورسیه از انجمن درخواست می‌دهم.",
        "expect_question": True,
        "question_token": "درخواست",
        "expect_intent": "scholarship",
        "expect_rtl": True,
    },
    {
        "id": "sv-explicit-private-applicant-beats-association-funding-source",
        "lang": "sv",
        "width": 768,
        "text": "Jag är privatperson och söker bidrag från föreningen.",
        "expect_question": False,
        "expect_actor": "private",
        "reject_actor": "association",
        "expect_intent": "funding",
    },
    {
        "id": "sv-explicit-self-association-survives-other-association-funder",
        "lang": "sv",
        "width": 1024,
        "text": "Vår förening söker bidrag från en annan förening.",
        "expect_question": False,
        "expect_actor": "association",
        "expect_intent": "funding",
    },
]

base.SCENARIOS.extend(EXTRA_SCENARIOS)


if __name__ == "__main__":
    raise SystemExit(base.main())